### ISSUE TITLE
Multiplayer inventories not showing

### ISSUE THREAD

**Issue by gerritdevriese** [gucci-on-fleek/Stardew-Valley-Item-Finder#2]
### Describe the bug
In co-op save files the "Stored in" column only shows the hosts inventory, even though there are multiple other players that definitely have items in their inventories.

### Browser and OS
Tested on both Arch Linux with Firefox 101.0.1 (64-bit) and Windows 10 with Chrome, both have this problem.

### Save file
Tested with two separate save files, issue appears in both.

**Comment by gucci-on-fleek** [comment]
The fix for this should be live. The cache for [`items-to-csv.xslt`](https://github.com/gucci-on-fleek/Stardew-Valley-Item-Finder/blob/master/src/items-to-csv.xslt) is _really_ sticky though, so you may need to wait 24 hours to see anything.

I also don't really have any decent multiplayer save files for testing, so please let me know if anything is broken or you have any suggestions for improvement.

**Comment by gerritdevriese** [comment]
It is working perfectly now with our save file with 4 players (also tool items)
Thank you very much!
